/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import memedream.*;
import memedream.Thumbnail;
import java.awt.BorderLayout;
import java.awt.ComponentOrientation;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;
import static javax.swing.ScrollPaneConstants.*;

/**
 *
 * @author Willi
 */
public class GalleryView extends javax.swing.JPanel {

    /**
     * Creates new form GalleryView
     */
    public GalleryView() {
        initComponents();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GalleryScroll = new javax.swing.JScrollPane();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GalleryScroll)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GalleryScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // adds labels to grid
    // should be replaced by add image
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        thumbCount++;
        labels.add(new Thumbnail("I am number " + thumbCount));
        update(labels);
    }//GEN-LAST:event_addButtonActionPerformed
    
    // <editor-fold defaultstate="collapsed" desc="Custom 'InitComponents'">
    private void addComponents(){
        labels = new ArrayList<>();
        
        buttons = new JPanel();
        buttons.setLayout(new FlowLayout());
        
        addButton = new JButton ("add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        removeButton = new JButton("remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        panel = new JPanel();
        GalleryScroll.setViewportView(panel);
        GalleryScroll.setVerticalScrollBarPolicy(VERTICAL_SCROLLBAR_ALWAYS);
        GalleryScroll.setHorizontalScrollBarPolicy(HORIZONTAL_SCROLLBAR_NEVER);
        panelLayout = new GridLayout(0,3,5,5);
        panel.setLayout(panelLayout);
        
        labels.add(new Thumbnail());
        
        panel.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
        buttons.add(addButton);
        buttons.add(removeButton);
        this.add(buttons, BorderLayout.SOUTH);
        
        update(labels);
    }//</editor-fold>
    
    // "removes" the labels
    // should be replaced by remove image
    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt){
        if(thumbCount >= 1){
            thumbCount--;
            Thumbnail del = labels.get(labels.size()-1);
            labels.remove(del);
        }
        update(labels);
    }
    
    
    private void update(ArrayList<Thumbnail> labels) {
        panel.removeAll();
        labels.forEach((n)->{
            panel.add(n);
        });
        
        panel.revalidate();
        panel.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane GalleryScroll;
    private javax.swing.JButton addButton;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
    private JPanel panel;
    private JPanel buttons;
    private GridLayout panelLayout;
    private ArrayList<Thumbnail> labels; 
    private int thumbCount = 0;
    
}
